services:
  bootstrap1:
    image: bootstrap_server:latest
    container_name: bootstrap1
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: boot
    environment:
      - SERVICE=boot
    network_mode: host  # Use host network
    command: [
      "./boot",
      "-port=1237",
      "-key=0"
    ]

  bootstrap2:
    image: bootstrap_server:latest
    container_name: bootstrap2
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: boot
    environment:
      - SERVICE=boot
    network_mode: host  # Use host network
    command: [
      "./boot",
      "-port=1238",
      "-key=1",
      "-bootstrap=/ip4/192.168.65.3/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n"
    ]
    depends_on:
      - bootstrap1

  bootstrap3:
    image: bootstrap_server:latest
    container_name: bootstrap3
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: boot
    environment:
      - SERVICE=boot
    network_mode: host  # Use host network
    command: [
      "./boot",
      "-port=1239",
      "-key=2",
      "-bootstrap=/ip4/192.168.65.3/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n,/ip4/192.168.65.3/tcp/1238/p2p/12D3KooWBnext3VBZZuBwGn3YahAZjf49oqYckfx64VpzH6dyU1p"
    ]
    depends_on:
      - bootstrap1
      - bootstrap2

  relay:
    image: relay_node:latest
    container_name: relay
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: relay
    environment:
      - SERVICE=relay
    network_mode: host
    command: [
      # "./relay",
      "some",
      "3",
      "/ip4/192.168.65.3/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n",
      "/ip4/192.168.65.3/tcp/1238/p2p/12D3KooWBnext3VBZZuBwGn3YahAZjf49oqYckfx64VpzH6dyU1p",
      "/ip4/192.168.65.3/tcp/1239/p2p/12D3KooWDKYjXDDgSGzhEYWYtDvfP9pMtGNY1vnAwRsSp2CwCWHL"
    ]
    depends_on:
      - bootstrap1
      - bootstrap2
      - bootstrap3

  node_runner:
    image: node_runner:latest
    container_name: node_runner
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: node_runner
    environment:
      - SERVICE=node_runner
    depends_on:
      - bootstrap1
      - bootstrap2
      - bootstrap3
      - relay
    command: [
      # "./node_runner",
      "/ip4/192.168.65.3/tcp/1240/p2p/12D3KooWRnBKUEkAEpsoCoEiuhxKBJ5j2Bdop6PGxFMvd4PwoevM",
      "7",
      "/ip4/192.168.65.3/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n",
      "/ip4/192.168.65.3/tcp/1238/p2p/12D3KooWBnext3VBZZuBwGn3YahAZjf49oqYckfx64VpzH6dyU1p",
      "/ip4/192.168.65.3/tcp/1239/p2p/12D3KooWDKYjXDDgSGzhEYWYtDvfP9pMtGNY1vnAwRsSp2CwCWHL"
    ]
    networks:
      noderunner-net:
        ipv4_address: 172.20.0.2

  mobile_client:
    image: mobile_client:latest
    container_name: mobile_client
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE: mobile_client
    environment:
      - SERVICE=mobile_client
    depends_on:
      - bootstrap1
      - bootstrap2
      - bootstrap3
      - relay
      - node_runner
    command: [
      # "./mobile_client",
      "/ip4/192.168.65.3/tcp/1240/p2p/12D3KooWRnBKUEkAEpsoCoEiuhxKBJ5j2Bdop6PGxFMvd4PwoevM",
      "8",
      "/ip4/192.168.65.3/tcp/1237/p2p/12D3KooWLr1gYejUTeriAsSu6roR2aQ423G3Q4fFTqzqSwTsMz9n",
      "/ip4/192.168.65.3/tcp/1238/p2p/12D3KooWBnext3VBZZuBwGn3YahAZjf49oqYckfx64VpzH6dyU1p",
      "/ip4/192.168.65.3/tcp/1239/p2p/12D3KooWDKYjXDDgSGzhEYWYtDvfP9pMtGNY1vnAwRsSp2CwCWHL"
    ]
    networks:
      mobile-net:
        ipv4_address: 172.21.0.2

networks:
  noderunner-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

  mobile-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
